# Generated by Django 4.2.5 on 2023-09-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Juego',
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Usuario_datos',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.RenameField(
            model_name='juego',
            old_name='comision',
            new_name='año',
        ),
    ]
