# Generated by Django 4.2.5 on 2023-09-25 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_rename_curso_juego_rename_profesor_usuario_datos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido',
            new_name='password',
        ),
    ]
